services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    networks:
      - net1
    environment:
      MYSQL_ROOT_PASSWORD: 14789
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-replication/master/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-replication/master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-replication/certs:/etc/mysql/certs
      - master_db:/var/lib/mysql

  slave:
    image: mysql:8.0
    container_name: mysql-slave
    networks:
      - net1
    environment:
      MYSQL_ROOT_PASSWORD: 14789
    ports:
      - "3308:3306"
    depends_on:
      - master
    volumes:
      - ./mysql-replication/slave/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql-replication/slave/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-replication/certs:/etc/mysql/certs
      - slave_db:/var/lib/mysql

  proxysql:
    image: proxysql/proxysql:2.6.3
    container_name: proxysql
    networks:
      - net1
    depends_on:
      - master
      - slave
    ports:
      - "6033:6033"   # для Spring Boot
      - "6032:6032"   # админка ProxySQL
    volumes:
      - ./mysql-replication/proxysql.cnf:/etc/proxysql.cnf
      - ./mysql-replication/certs:/etc/mysql/certs

volumes:
  master_db:
  slave_db:

networks:
  net1: