services:
  mysite1:
    image: mysite
    container_name: mysite1
    ports:
      - "8081:8080"
    networks:
      - net1
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/bootdb
      SPRING_DATASOURCE_PASSWORD: 14789
      SPRING_MAIL_PASSWORD: 9WxWtRuBtTxue8k35va9
    volumes:
      - /home/karina/ProgJava/imagecab:/app/imagecab:rw
    depends_on:
      - mysqldb


  mysite2:
    image: mysite
    container_name: mysite2
    ports:
      - "8082:8080"
    networks:
      - net1
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/bootdb
      SPRING_DATASOURCE_PASSWORD: 14789
      SPRING_MAIL_PASSWORD: 9WxWtRuBtTxue8k35va9
    volumes:
      - /home/karina/ProgJava/imagecab:/app/imagecab:rw
    depends_on:
      - mysqldb

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysite1
      - mysite2
    networks:
      - net1


  mysqldb:
    image: mysql:8
    container_name: mysqldb
    ports:
      - "3307:3306"
    networks:
      - net1
    environment:
      - MYSQL_ROOT_PASSWORD=14789
      - MYSQL_DATABASE=bootdb
    volumes:
      - db:/var/lib/mysql

networks:
  net1:

volumes:
  db:

