services:
  mysite1:
    image: mysite
    container_name: mysite1
    ports:
      - "8081:8080"
    networks:
      - net1
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/bootdb
      SPRING_DATASOURCE_PASSWORD: 14789
      SPRING_MAIL_PASSWORD: 9WxWtRuBtTxue8k35va9
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    volumes:
      - /home/karina/ProgJava/imagecab:/app/imagecab:rw


  mysite2:
    image: mysite
    container_name: mysite2
    ports:
      - "8082:8080"
    networks:
      - net1
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/bootdb
      SPRING_DATASOURCE_PASSWORD: 14789
      SPRING_MAIL_PASSWORD: 9WxWtRuBtTxue8k35va9
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    volumes:
      - /home/karina/ProgJava/imagecab:/app/imagecab:rw

  redis:
    image: redis:7
    container_name: redis
    networks:
      - net1
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  redis_data:

networks:
  net1:


