services:
 proxysql:
  image: proxysql/proxysql:2.6.3
  container_name: proxysql
  networks:
    - net1
  ports:
    - "6032:6032"
    - "6033:6033"
  volumes:
    - ./mysql_replication/proxysql/proxysql.cnf:/etc/proxysql.cnf
    - ./mysql_replication/proxysql/init_proxysql.sql:/docker-entrypoint-initdb.d/init.sql


  entrypoint: [ "/usr/bin/proxysql", "-f", "-c", "/etc/proxysql.cnf" ]


networks:
  net1:

