services:
  mysql-slave1:
    image: mysql:8.0
    container_name: mysql-slave1
    networks:
      - net1
    environment:
      MYSQL_ROOT_PASSWORD: 147891
    volumes:
      - slave1_data:/var/lib/mysql
      - ./mysql_replication/slave1/my.cnf:/etc/mysql/conf.d/my.cnf

    ports:
      - "3308:3306"

  mysql-slave2:
      image: mysql:8.0
      container_name: mysql-slave2
      networks:
        - net1
      environment:
        MYSQL_ROOT_PASSWORD: 147891
      volumes:
        - slave2_data:/var/lib/mysql
        - ./mysql_replication/slave2/my.cnf:/etc/mysql/conf.d/my.cnf

      ports:
        - "3309:3306"

  proxysql:
      image: proxysql/proxysql:2.6.3
      container_name: proxysql
      networks:
        - net1
      ports:
        - "6032:6032"
        - "6033:6033"
      volumes:
        - ./mysql_replication/proxysql/proxysql.cnf:/etc/proxysql.cnf
        - ./mysql_replication/proxysql/init_proxysql.sql:/docker-entrypoint-initdb.d/init.sql


      entrypoint: [ "/usr/bin/proxysql", "-f", "-c", "/etc/proxysql.cnf" ]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - net1
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
    slave1_data:
    slave2_data:
    redis_data:

networks:
  net1:
    external: true

