apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  labels:
    app: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: {{ .Values.redis.cluster.nodes }}
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          command:
            - "redis-server"
          args:
            - "/etc/redis/redis.conf"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            - "--masterauth"
            - "$(REDIS_PASSWORD)"
            - "--cluster-announce-ip"
            - "$(POD_IP)"
          ports:
            - containerPort: {{ .Values.redis.port }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis/
          resources:
            {{- toYaml .Values.resources | nindent 10 }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -a $REDIS_PASSWORD ping"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -a $REDIS_PASSWORD ping | grep PONG"
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: redis-config
          configMap:
            name: redis-cluster-config