spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liAVrpgakwpzRqQ4
            clientSecret: e92ca3c865a3eff4951723adb0eb8da26329667a
            scope: read:user, user:email
            #redirect-uri: "{baseUrl}/login/oauth2/code/github"
        #provider:
          #github:
            #authorization-uri: https://github.com/login/oauth/authorize
            #token-uri: https://github.com/login/oauth/access_token
            #user-info-uri: https://api.github.com/user
