spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liAVrpgakwpzRqQ4
            clientSecret: e92ca3c865a3eff4951723adb0eb8da26329667a
            scope: read:user, user:email
            #redirect-uri: "{baseUrl}/login/oauth2/code/github"
        #provider:
          #github:
            #authorization-uri: https://github.com/login/oauth/authorize
            #token-uri: https://github.com/login/oauth/access_token
            #user-info-uri: https://api.github.com/user


  redis:
    #host: redis
    host: localhost
    port: 6379
    timeout: 2000ms  # 2 секунды

  session:
   store-type: redis
   redis:
     flush-mode: immediate
     save-mode: on_set_attribute
     namespace: spring:session

server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: passkeystore
    key-store-type: PKCS12
  address: 0.0.0.0
  port: 8443
  servlet:
    session:
      timeout: 30m
      cookie:
        name: SESSION
        http-only: true
        same-site: none
        secure: true
  forward-headers-strategy: framework

