--INSERT INTO roles (name) VALUES ('ADMIN'), ('USER'), ('BLOCKED');
INSERT INTO roles (name)
SELECT 'ADMIN' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ADMIN');

INSERT INTO roles (name)
SELECT 'USER' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'USER');

INSERT INTO roles (name)
SELECT 'BLOCKED' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'BLOCKED');